# Adapted from github.com:debug-ito/staversion/.github/workflows/haskell.yml

name: Stack build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  stack:
    name: ${{ matrix.os }} Stack ${{ matrix.plan.resolver }} / ${{ matrix.plan.ghc }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        plan:
          - ghc: '9.10.1'
            resolver: 'nightly-2025-05-02'
          - ghc: '9.8.4'
            resolver: 'lts-23.20'
          - ghc: '9.6.7'
            resolver: 'lts-22.44'
          - ghc: '9.4.8'
            resolver: 'lts-21.25'
          - ghc: '9.2.8'
            resolver: 'lts-20.26'
          - ghc: '9.0.2'
            resolver: 'lts-19.33'
          - ghc: '8.10.7'
            resolver: 'lts-18.28'
          - ghc: '8.8.4'
            resolver: 'lts-16.31'
          - ghc: '8.6.5'
            resolver: 'lts-14.27'
          - ghc: '8.4.4'
            resolver: 'lts-12.26'

        include:
          - os: windows-latest
            plan:
              resolver: 'nightly-2025-05-02'
              ghc: '9.10.1'
          - os: windows-latest
            plan:
              resolver: 'lts-22.44'
              ghc: '9.6.7'

          - os: macos-latest
            plan:
              resolver: 'nightly-2025-05-02'
              ghc: '9.10.1'
          - os: macos-latest
            plan:
              resolver: 'lts-22.44'
              ghc: '9.6.7'

    runs-on: ${{ matrix.os }}
    env:
      STACK: stack --no-terminal --system-ghc --resolver ${{ matrix.plan.resolver }}

    steps:
    - uses: actions/checkout@v4

    # windows/macos no longer have stack preinstalled
    - uses: haskell-actions/setup@v2
      with:
        ghc-version: ${{ matrix.plan.ghc }}
        enable-stack: true
        cabal-update: false

    - name: Configure
      run: $STACK init

    - name: Install GHC via stack (or make sure it is installed)
      run: $STACK ghc -- --version

    # - name: Haskell versions
    #   run: |
    #     STACK_VERSION=$(${STACK} --numeric-version)
    #     echo "STACK_VERSION=${STACK_VERSION}" >> "${GITHUB_ENV}"
    #     GHC_VERSION=$(${STACK} ghc -- --numeric-version)
    #     echo "GHC_VERSION=${GHC_VERSION}" >> "${GITHUB_ENV}"

      ## This causes troubles on Windows (spaces in env variable)?
      # STACK_ROOT=$(${STACK} path --stack-root)
      # echo "STACK_ROOT=${STACK_ROOT}" >> "${GITHUB_ENV}"

    ## Caching ~/.stack without --system-ghc is probably not a good idea:
    ## - too fat
    ## - should be sensibly restored before installing GHC via stack,
    ##   but then we don't know the GHC version; so at least 'lts' and 'nightly' would be brittle
    ##
    # - uses: actions/cache@v3
    #   with:
    #     path: ${{ env.STACK_ROOT }}
    #     key: ${{ runner.os }}-stack-${{ env.STACK_VERSION }}-ghc-${{ env.GHC_VERSION }}-resolver-${{ matrix.plan.resolver }}

    - name: Install dependencies
      run: $STACK test --only-dependencies

    - name: Build
      run: $STACK build --haddock --no-haddock-deps

    - name: Test
      run: $STACK -j 1 test --haddock --no-haddock-deps
